import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import CustomToast from "./_components/CustomToast";
import { Toaster } from "@/components/ui/sonner";
// charts/setup.ts (import this somewhere at app startup)


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rango Assignment",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased`}>
        {children}
        <Toaster />
        <CustomToast />
      </body>
    </html>
  );
}
